Update phoebe.spec
SUSE/phoebe pull request #18
Opened 2021-01-18 18:19 UTC by mge1512

phoebe.spec as tested in OpenBuildService.

2021-01-18 19:15 UTC, dcermak requested changes
Thanks for the PR @mge1512! I've added a few suggestions how the spec can be simplified.

2021-01-18 19:15 UTC, dcermak commented on dist/rpm/phoebe.spec
> +%setup -q
```suggestion
%autosetup
```

2021-01-18 19:15 UTC, dcermak commented on dist/rpm/phoebe.spec
> +meson build
Otherwise the correct optflags will not be set
```suggestion
%meson
```

2021-01-18 19:15 UTC, dcermak commented on dist/rpm/phoebe.spec
> +cd build
```suggestion
```

2021-01-18 19:15 UTC, dcermak commented on dist/rpm/phoebe.spec
> +meson compile
```suggestion
%meson_build
```

2021-01-18 19:15 UTC, dcermak commented on dist/rpm/phoebe.spec
> +%doc OWNERS README.md CONTRIBUTING.md SETUP.md
`OWNERS` and `CONTRIBUTING.md` are not really useful for end user documentation.

```suggestion
%doc README.md SETUP.md
```

2021-01-18 19:15 UTC, dcermak commented on dist/rpm/phoebe.spec
> +Version:        0.0.4
```suggestion
Version:        0.1
```

2021-01-18 19:15 UTC, dcermak commented on dist/rpm/phoebe.spec
> +Release:        0.3
At least for building on OBS, the release tag is ignored and set by the build system.
```suggestion
Release:        0
```

2021-01-18 19:15 UTC, dcermak commented on dist/rpm/phoebe.spec
> +Source:         phoebe-%version.tar.xz
This way spectool can download the latest version directly:

```suggestion
Source:         %{URL}/archive/v%{version}.tar.gz#/%{name}-%{version}.tar.gz
```

2021-01-18 19:15 UTC, dcermak commented on dist/rpm/phoebe.spec
> +mkdir -p /${RPM_BUILD_ROOT}/%{_bindir}
This can all be replaced with `%meson_install`

2021-01-18 19:15 UTC, dcermak commented on dist/rpm/phoebe.spec
> +Group:          System/Benchmark
The Group tag is obsolete:
```suggestion
```

2021-01-19 07:08 UTC, mvarlese commented
Thanks @mge1512 

@dcermak I like the idea to have the SPEC file merged as all the changes look more as nice-to-have than roadblocks. In that way, we could refine the SPEC file later. Also consider the SPEC file is working just fine as a package is already being built in OBS.

2021-01-19 07:08 UTC, merged